### ISSUE TITLE
settings for ~/.nylas/config.cson

### ISSUE THREAD

**Issue by Analect** [nhurel/nylas-n1-builder#1]
Thanks for this great resource.
The commands in the README may want to reflect the new version 0.4.5

So `docker cp n1:/tmp/nylas-build/nylas-0.4.5-amd64.deb .`  
and `docker cp n1:/tmp/nylas-build/nylas-0.4.5-0.1.x86_64.rpm .`

I was wondering if you might have some guidance on the format of the config.cson, if you happen to have a working/running version.

In your readme, you use `env: "selfhosted"` and back on the N1 site they use `env:"local"` ... I have tried both .. without success. The sync-engine container is running and exposing to localhost:5555, so I haven't explicitly added that in the config file.

Also, when I first run Nylas (without an over-riding config file already in place), it generates a basic one that includes `disabledPackages [ ...]` and and `updateIdentity: "xyz ..."`

I have copied these across the the new config file ... and also removed the `compile-cache` folder .. so the original config settings are removed. I'm trying with and without this `updateIdentity`, but neither work.

Issues 185 and 398 on the nylas/N1 repo address this same issue, but neither offers a working solution. As was suggested on there ... I'm using spaces and not tabs and have removed white-spaces etc... 

I'd be very appreciative if you see any glaring errors I might be making. Thanks.

```
"*":
  env: "local"
  core:
    disabledPackages: [
      "quick-schedule"
      "composer-templates"
      "composer-translate"
      "message-view-on-github"
      "personal-level-indicators"
      "phishing-detection"
      "github-contact-card"
    ]
    disabledPackagesInitialized: true
  updateIdentity: "long-string-id"
  nylas:
    accounts: [
      {
        account_id: "long-string-acc-id",
        email_address: "my_email@gmail.com",
        id: "same as long-string acc id above",
        name: "My name",
        object: "account",
        organization_unit: "label",
        provider: "gmail",
        sync_state: "running"
     }
    ]
    accountTokens:
    "same as acc id above": "same as acc id above"
```

**Comment by nhurel** [comment]
If you're running sync-engine locally, you don't need to build the package by yourself with this container, you can simply use the N1 package distributed by Nylas, and set env to "local". Building your own should also work, though.

Regarding your `config.cson` file, you don't need the comma `,` at the end of each line in the account element, nor the `sync_state` property, but you should add the `server_id` property, with same value as`id` and `account_id`.

You can start N1 with `/usr/share/nylas/nylas` in a terminal. It should give you some logs when it fails to parse your `config.cson` file.

Good luck !

**Comment by Analect** [comment]
I had missed adding the `server_id` too ... seems odd you would have to set three variables to the same value in the config ... anyway, it worked.  Also, it complained about the key:value for `accountTokens` not being on the same line ... anyway up and running. Thanks for your input. I'll close this out.
